name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GUM_OPTIONS: '-Dfrida-gum:gumjs=enabled'

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [amd64_x86, amd64]
      fail-fast: false
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Build
        run: |
          npm install
          cd test
          npm install
          .\configure -- ${{ env.GUM_OPTIONS }}
          .\make
      - name: Test
        run: .\test\build\frida-fs-tests.exe

  macos-x86_64:
    runs-on: macos-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Build
        run: |
          npm install
          cd test
          npm install
          ./configure -- ${{ env.GUM_OPTIONS }}
          make
      - name: Test
        run: ./test/build/frida-fs-tests

  linux-x86:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib lib32stdc++-13-dev
      - name: Build
        run: |
          npm install
          cd test
          npm install
          CC="gcc -m32" CXX="g++ -m32" STRIP="strip" \
              ./configure --build=linux-x86 --host=linux-x86 -- ${{ env.GUM_OPTIONS }}
          make
      - name: Test
        run: ./test/build/frida-fs-tests

  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Build
        run: |
          npm install
          cd test
          npm install
          ./configure -- ${{ env.GUM_OPTIONS }}
          make
      - name: Test
        run: ./test/build/frida-fs-tests

  linux-armhf:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install g++-arm-linux-gnueabihf qemu-user
      - name: Build
        run: |
          npm install
          cd test
          npm install
          ./configure --host=arm-linux-gnueabihf -- ${{ env.GUM_OPTIONS }}
          make
      - name: Test
        run: qemu-arm -L /usr/arm-linux-gnueabihf ./test/build/frida-fs-tests

  linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install g++-aarch64-linux-gnu qemu-user
      - name: Build
        run: |
          npm install
          cd test
          npm install
          ./configure --host=aarch64-linux-gnu -- ${{ env.GUM_OPTIONS }}
          make
      - name: Test
        run: qemu-aarch64 -L /usr/aarch64-linux-gnu ./test/build/frida-fs-tests
